name: Integration workflow

on:
  push:
    branches:
      - integration
      - test_pipeline # TODO: remove 

# Here the environment variable is declared in workflow level
env:
  # TODO: Replace with our Orchestrator Values
  # PROJECT_NAME: uipath.github.action 
  # PROJECT_FOLDER: ${{ github.action_path }}
  ORCH_URL: "https://cloud.uipath.com/"
  ORCH_TENANT: ${{ secrets.UIPATHTENANTNAME }}
  ORCH_CLIENT_ID: ${{ secrets.UIPATHCLIENTID }}
  ORCH_USER_KEY: ${{ secrets.UIPATHUSERKEY }}
  ORCH_ACC_NAME: ${{ secrets.UIPATHACCOUNTNAME }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID}}
  OAUTH_CLIENT_SCOPES: ${{ secrets.OAUTH_CLIENT_SCOPES}}
  OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET}}

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"

  # clean-previous:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Runner workspace path
  #       run: |
  #         echo "Cleaning up previous run"
  #         rm -rf "${{ github.workspace }}"

  remove-old-artifacts:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'        

  build: 
    runs-on: windows-latest
    needs: remove-old-artifacts
    steps:            
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v2    

      # Facilitate the UiPath CLI in the github artifacts
      - name: Setup UiPath CLI
        uses: Mikael-RnD/setup-uipath@v1.0.0
        with:
            version: 1.0.7985.19721 

       # Action for packing UiPath projects in a repository
      - name: UiPath Pack
        uses: Mikael-RnD/UiPath-Pack@main
        with:
          orchestratorUrl: env.ORCH_URL
          orchestratorTenant: env.ORCH_TENANT
          orchestratorFolder: "Metamarian" 
          orchestratorApplicationId: env.OAUTH_CLIENT_ID
          orchestratorApplicationSecret: env.OAUTH_CLIENT_SECRET
          orchestratorApplicationScope: env.OAUTH_CLIENT_SCOPES
          orchestratorLogicalName: "tudorcosminfoundation"
          projectVersion: 1.0.8     